import "./globals.css";
import styles from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <div className="logo">
            <h2>LogoM</h2>
          </div>
          <div className="navlinks">
            <a href="/">Movies</a>
            <a href="/tvshows">Tv Shows</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
